--- #YAML:1.0
name:               XML-Encoding
version:            2.08
abstract:           A perl module for parsing XML encoding maps.
author:
    - Clark Cooper (coopercc@netheaven.com), Steve Hay (shay@cpan.org)
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    XML::Parser:  2.18
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
