--- #YAML:1.0
name:                XML-Encoding
version:             2.07
abstract:            A perl module for parsing XML encoding maps.
license:             perl
author:              
    - Clark Cooper (coopercc@netheaven.com), Steve Hay (shay@cpan.org)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    XML::Parser:                   2.18
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
